"""empty message

Revision ID: 3369f27c86ef
Revises: da30db10b4ba
Create Date: 2024-04-21 23:17:59.219268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3369f27c86ef'
down_revision = 'da30db10b4ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_chat_room_project_id', 'project', ['project_id'], ['id'])
        batch_op.create_foreign_key('fk_chat_room_role_id', 'role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_room_project_id', type_='foreignkey')
        batch_op.drop_constraint('fk_chat_room_role_id', type_='foreignkey')

    # ### end Alembic commands ###