"""empty message

Revision ID: 80b38f177eff
Revises: 0f9bf7bd0eb9
Create Date: 2024-04-17 23:32:05.950430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b38f177eff'
down_revision = '0f9bf7bd0eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_room_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('chat_room_id')

    # ### end Alembic commands ###
