"""empty message

Revision ID: b4fb29817410
Revises: 0636092e33d3
Create Date: 2024-03-05 15:42:47.134102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4fb29817410'
down_revision = '0636092e33d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_post', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
