"""empty message

Revision ID: da30db10b4ba
Revises: 80b38f177eff
Create Date: 2024-04-17 23:36:41.504224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da30db10b4ba'
down_revision = '80b38f177eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('chat_room_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_room_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
