"""empty message

Revision ID: e0687f51dffb
Revises: b4fb29817410
Create Date: 2024-03-05 15:44:30.228923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0687f51dffb'
down_revision = 'b4fb29817410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_post', schema=None) as batch_op:
        batch_op.drop_column('location')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('location')

    with op.batch_alter_table('project_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
